export const paths = [
  {
    n: '01',
    title: 'Instant Estimate',
    tag: null,
    body: 'Instant Estimate uses guided questions to organize a process that cannot truly be standardized. It provides rough pricing ranges based on your responses, but these are not quotes for service. Its purpose is to help identify the path that best fits your situation and guide you toward the next step..',
    cta: { label: 'Get an Instant Estimate', href: '/estimate/instant' },
    details: [
      'Based on your multiple choice answers',
      'No physical examination',
      'Results are immediate',
      'Best for: curious owners, quick ballpark figures',
      'When you need a service recommendation',
    ],
  },
  {
    n: '02',
    title: 'Online Estimate',
    tag: null,
    warning: null,
    body: 'An extension of the instant estimate. Add photos and a description for our team to review!',
    cta: { label: 'Request an Online Estimate', href: '/estimate/online' },
    details: [
      'Sign up for s CCG Account for free.',
      'Add Photos to your Instant Results',
      'Check out and recieve an answer in 24 hours',
      'More accurate than an instant estimate',
      'Best for: owners who want more accurate numbers without shipping',
    ],
  },
  {
    n: '03',
    title: 'In-Person Estimate',
    tag: 'Recommended',
    warning: null,
    body: 'The most accurate estimate available. Send your gemstone to us for a physical examination. A work order is opened and an estimate is provided within 24–48 hours of receipt. In-person estimates are free.',
    cta: { label: 'Open a Work Order', href: '/account' },
    details: [
      'Physical examination of your stone',
      'Estimate within 24–48 hours of receipt',
      'Client covers shipping and provides tracking number',
      'SMS notifications required',
      'Free of charge',
      'Best for: anyone serious about cutting or recutting',
    ],
  },
  {
    n: '04',
    title: 'CCG Feasibility Breakdown',
    tag: null,
    warning: null,
    body: ' This is not an actual estimate, It is instead a structural evaluation of your gemstone. We examine the stone to determine what cutting options are realistically possible, what risks may exist, and what results the material can actually support.',
    cta: { label: 'Different Types', href: '/feasibility-report' },
    details: [
      'Physical report style explainer.',
      'Crown, pavilion, and profile plots',
      'Recovery range and cutting approach options',
      'Can be used alongside other gem documentation for resale',
      'Available to cutting houses to build trust with clients by offering second opinions',
      'Standalone or bundled with services',
      'Best for: serious collectors, dealers, trade professionals',
    ],
  },
];

export type EstimatePath = typeof paths[0];
