// components/account/mobile/drawers/3WizardResultDrawer.tsx
// Converted from <!-- WIZARD RESULT DRAWER --> in account-dashboard-v3.html
//
// Right-slide drawer. Opens when the user taps a result in the wizard
// results panel (3WizardResultsPanel.tsx).
//
// Uses CSS classes: res-drawer, res-handle, res-body, res-topbar,
// res-band-badge, res-close, res-scroll, res-hero, res-ring, res-ring-num,
// res-stone-name, res-stone-meta, res-rec, res-section, res-section-label
// All defined in MobileShell.css.
//
// The entire drawer responds to swipe right to close.
//
// HTML → JSX changes:
//   class=      → className=
//   onclick=    → onClick=
//   style="..." → style={{ camelCase }}

import type { WizardResult } from '../../../../lib/wizardResultsService';
import { useSwipeToClose } from '../../shared/hooks/useSwipeToClose';
import FirstTimeTips from '../ui/FirstTimeTips';

interface WizardResultDrawerProps {
  open:                    boolean;
  result:                  WizardResult | null;
  onClose:                 () => void;
  onCreateServiceRequest?: (result: WizardResult) => void;
}

// Band colors -- match the colors used in the results panel and mockup
const BAND_COLOR: Record<string, string> = {
  '80-100': '#38bdf8',
  '60-79':  '#4ec994',
  '40-59':  '#a3e635',
  '18-39':  '#67e8f9',
  '0-17':   '#f87171',
};

const BAND_LABEL: Record<string, string> = {
  '80-100': 'Polish Only',
  '60-79':  'Stone Repair',
  '40-59':  'Partial Recut',
  '18-39':  'Full Recut',
  '0-17':   'No Recut Recommended',
};

// Large score ring -- 72x72px, used in the hero section at top of drawer
// Converted from the SVG generated by openResDrawer() in the HTML JS
function HeroRing({ pct, color }: { pct: number; color: string }) {
  const r      = 45;
  const circ   = 2 * Math.PI * r;
  const offset = circ * (1 - pct / 100);
  return (
    // res-ring: the ring wrapper with absolute-positioned number overlay
    <div className="res-ring">
      <svg width="100" height="100" viewBox="0 0 100 100">
        {/* Background track */}
        <circle cx="50" cy="50" r={r} fill="none" stroke="var(--border)" strokeWidth="4" />
        {/* Progress arc */}
        <circle
          cx="50" cy="50" r={r}
          fill="none" stroke={color} strokeWidth="4"
          strokeDasharray={circ}
          strokeDashoffset={offset}
          strokeLinecap="round"
          transform="rotate(-90 50 50)"
        />
      </svg>
      {/* res-ring-num: percentage centered over the ring */}
      <div className="res-ring-num" style={{ color, fontSize: '2.0rem' }}>{pct}</div>
    </div>
  );
}

// A checkmark list item -- used for positive, limiting, structural sections
// Converted from the listItems() function in openResDrawer()
function ListItem({ text, color }: { text: string; color?: string }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: 10,
      padding: '8px 0', borderBottom: '0.5px solid var(--border)',
    }}>
      <span style={{ color: color || 'var(--gold)', fontSize: '0.75rem', flexShrink: 0, marginTop: 1 }}>✓</span>
      <span style={{ fontFamily: 'var(--font-ui-mob)', fontSize: '0.8125rem', color: 'var(--text)' }}>{text}</span>
    </div>
  );
}

// A section with a mono uppercase label and content below
// Converted from the section() function in openResDrawer()
function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="res-section">
      {/* res-section-label: uppercase mono label with bottom border */}
      <div className="res-section-label" style={{ color: 'var(--text-muted)' }}>{label}</div>
      {children}
    </div>
  );
}

export default function WizardResultDrawer3({
  open, result, onClose, onCreateServiceRequest,
}: WizardResultDrawerProps) {

  // ── Swipe to close ──
  const { elementRef, touchHandlers } = useSwipeToClose({ onClose });

  if (!result) return null;

  const pct   = Math.round(result.feasibility_percent);
  const color = BAND_COLOR[result.band] ?? '#67e8f9';
  const label = BAND_LABEL[result.band] ?? result.recommendation;
  const stone = [result.stone_variety, result.stone_species].filter(Boolean).join(' ') || 'Unnamed stone';
  const weight = result.stone_weight_ct ? `${result.stone_weight_ct} ct` : '--';
  const date  = new Date(result.created_at).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  });

  // Selections come from the wizard_results table as jsonb arrays/objects.
  // Supabase's JS client auto-parses jsonb so these are real JS arrays/objects.
  const positive:   string[] = Array.isArray(result.positive_selections)   ? result.positive_selections   : [];
  const limiting:   string[] = Array.isArray(result.limiting_selections)   ? result.limiting_selections   : [];
  const structural: string[] = Array.isArray(result.structural_selections) ? result.structural_selections : [];

  // Correctable selections is a map { issueKey: severity | null }.
  // Only show entries that actually have a non-null value.
  const correctableObj = (result.correctable_selections || {}) as Record<string, string | null>;
  const correctable: Array<{ key: string; val: string }> = Object.entries(correctableObj)
    .filter(([, v]) => v != null && v !== '')
    .map(([k, v]) => ({ key: k, val: v as string }));

  return (
    <>
      {/* Dark overlay */}
      <div className={`overlay${open ? ' open' : ''}`} onClick={onClose} />

      {/* res-drawer: right-slide container */}
      <div
        ref={elementRef}
        className={`res-drawer${open ? ' open' : ''}`}
        {...touchHandlers}
      >
        {/* res-handle: left drag zone -- visual indicator */}
        <div className="res-handle" />

        <FirstTimeTips type="drawer-slide" show={open} />
        {/* res-body: the main content area */}
        <div className="res-body">

          {/* res-topbar: band badge + stone name + close button */}
          {/* Converted from the topbar section of openResDrawer() */}
          <div className="res-topbar">
            <span style={{
              fontFamily: 'var(--font-mono-mob)', fontSize: '0.625rem',
              letterSpacing: '0.16em', textTransform: 'uppercase',
              color: 'var(--text-muted)', flex: 1,
            }}>
              {stone}
            </span>
            <button className="res-close" onClick={onClose}>✕</button>
          </div>

          {/* res-scroll: scrollable content area */}
          <div className="res-scroll">

            {/* res-hero: large ring + stone name + recommendation */}
            {/* Converted from the res-hero block injected by openResDrawer() */}
            <div className="res-hero">
              <HeroRing pct={pct} color={color} />
              <div>
                {/* res-stone-name: the stone name in display font */}
                <div className="res-stone-name">{stone}</div>
                {/* res-stone-meta: weight, cut, dimensions */}
                <div className="res-stone-meta">
                  {weight} · {result.stone_cut || '--'}<br />
                  {result.stone_dimensions || '--'}
                </div>
                {/* res-rec: the recommendation label in band color */}
                <div className="res-rec" style={{ color }}>{label}</div>
              </div>
            </div>

            {/* ── Positive characteristics ── */}
            {/* Converted from section('Positive Characteristics', listItems(r.positive)) */}
            <Section label="Positive Characteristics">
              {positive.length > 0 ? (
                positive.map((item, i) => <ListItem key={i} text={item} color="var(--gold)" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui-mob)', fontSize: '0.75rem', color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>

            {/* ── Limiting characteristics ── */}
            <Section label="Limiting Characteristics">
              {limiting.length > 0 ? (
                limiting.map((item, i) => <ListItem key={i} text={item} color="#f87171" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui-mob)', fontSize: '0.75rem', color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>

            {/* ── Structural condition ── */}
            <Section label="Structural Condition">
              {structural.length > 0 ? (
                structural.map((item, i) => <ListItem key={i} text={item} color="#fb923c" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui-mob)', fontSize: '0.75rem', color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>


            {/* Date stamp */}
            <div className="res-date">{date}</div>

            {/* Create Service Request button */}
            {/* Converted from the button injected at the bottom of openResDrawer() */}
            {onCreateServiceRequest && (
              <div style={{ marginTop: 24 }}>
                <button
                  onClick={() => onCreateServiceRequest(result)}
                  style={{
                    width: '100%', background: 'var(--gold)', color: 'var(--bg-deep)',
                    border: 'none', padding: 13, fontFamily: 'var(--font-mono-mob)',
                    fontSize: '0.625rem', letterSpacing: '0.22em', textTransform: 'uppercase',
                    cursor: 'pointer', transition: 'opacity 180ms ease',
                  }}
                  onMouseOver={e => { (e.currentTarget as HTMLButtonElement).style.opacity = '0.85'; }}
                  onMouseOut={e  => { (e.currentTarget as HTMLButtonElement).style.opacity = '1'; }}
                >
                  + Create Service Request
                </button>
              </div>
            )}

          </div>{/* end res-scroll */}
        </div>{/* end res-body */}
      </div>{/* end res-drawer */}
    </>
  );
}
