// components/account/mobile/drawers/3WizardResultDrawer.tsx
// Converted from <!-- WIZARD RESULT DRAWER --> in account-dashboard-v3.html
//
// Right-slide drawer. Opens when the user taps a result in the wizard
// results panel (3WizardResultsPanel.tsx).
//
// Uses CSS classes: res-drawer, res-handle, res-body, res-topbar,
// res-band-badge, res-close, res-scroll, res-hero, res-ring, res-ring-num,
// res-stone-name, res-stone-meta, res-rec, res-section, res-section-label
// All defined in MobileShell.css.
//
// HTML → JSX changes:
//   class=      → className=
//   onclick=    → onClick=
//   style="..." → style={{ camelCase }}

import { useRef } from 'react';
import type { WizardResult } from '../../../../lib/wizardResultsService';

interface WizardResultDrawerProps {
  open:                    boolean;
  result:                  WizardResult | null;
  onClose:                 () => void;
  onCreateServiceRequest?: (result: WizardResult) => void;
}

// Band colors -- match the colors used in the results panel and mockup
const BAND_COLOR: Record<string, string> = {
  '80-100': '#38bdf8',
  '60-79':  '#4ec994',
  '40-59':  '#a3e635',
  '18-39':  '#67e8f9',
  '0-17':   '#f87171',
};

const BAND_LABEL: Record<string, string> = {
  '80-100': 'Polish Only',
  '60-79':  'Stone Repair',
  '40-59':  'Partial Recut',
  '18-39':  'Full Recut',
  '0-17':   'No Recut Recommended',
};

// Large score ring -- 72x72px, used in the hero section at top of drawer
// Converted from the SVG generated by openResDrawer() in the HTML JS
function HeroRing({ pct, color }: { pct: number; color: string }) {
  const r      = 32;
  const circ   = 2 * Math.PI * r; // ≈ 201
  const offset = circ * (1 - pct / 100);
  return (
    // res-ring: the ring wrapper with absolute-positioned number overlay
    <div className="res-ring">
      <svg width="72" height="72" viewBox="0 0 72 72">
        {/* Background track */}
        <circle cx="36" cy="36" r={r} fill="none" stroke="var(--border)" strokeWidth="3" />
        {/* Progress arc */}
        <circle
          cx="36" cy="36" r={r}
          fill="none" stroke={color} strokeWidth="3"
          strokeDasharray={circ}
          strokeDashoffset={offset}
          strokeLinecap="round"
          transform="rotate(-90 36 36)"
        />
      </svg>
      {/* res-ring-num: percentage centered over the ring */}
      <div className="res-ring-num" style={{ color }}>{pct}</div>
    </div>
  );
}

// A checkmark list item -- used for positive, limiting, structural sections
// Converted from the listItems() function in openResDrawer()
function ListItem({ text, color }: { text: string; color?: string }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: 10,
      padding: '8px 0', borderBottom: '0.5px solid var(--border)',
    }}>
      <span style={{ color: color || 'var(--gold)', fontSize: 12, flexShrink: 0, marginTop: 1 }}>✓</span>
      <span style={{ fontFamily: 'var(--font-ui)', fontSize: 13, color: 'var(--text)' }}>{text}</span>
    </div>
  );
}

// A section with a mono uppercase label and content below
// Converted from the section() function in openResDrawer()
function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="res-section">
      {/* res-section-label: uppercase mono label with bottom border */}
      <div className="res-section-label" style={{ color: 'var(--text-muted)' }}>{label}</div>
      {children}
    </div>
  );
}

export default function WizardResultDrawer3({
  open, result, onClose, onCreateServiceRequest,
}: WizardResultDrawerProps) {

  // ── Swipe to close ──
  const startX    = useRef(0);
  const dragging  = useRef(false);
  const drawerRef = useRef<HTMLDivElement>(null);

  const onTouchStart = (e: React.TouchEvent) => {
    startX.current   = e.touches[0].clientX;
    dragging.current = false;
    if (drawerRef.current) drawerRef.current.style.transition = 'none';
  };
  const onTouchMove = (e: React.TouchEvent) => {
    const dx = e.touches[0].clientX - startX.current;
    if (!dragging.current && Math.abs(dx) > 6) dragging.current = true;
    if (dragging.current && dx > 0 && drawerRef.current) {
      drawerRef.current.style.transform = `translateX(${dx}px)`;
    }
  };
  const onTouchEnd = (e: React.TouchEvent) => {
    if (drawerRef.current) {
      drawerRef.current.style.transition = '';
      drawerRef.current.style.transform  = '';
    }
    const dx = e.changedTouches[0].clientX - startX.current;
    if (dragging.current && dx > 80) onClose();
    dragging.current = false;
  };

  if (!result) return null;

  const pct   = Math.round(result.feasibility_percent);
  const color = BAND_COLOR[result.band] ?? '#67e8f9';
  const label = BAND_LABEL[result.band] ?? result.recommendation;
  const stone = [result.stone_variety, result.stone_species].filter(Boolean).join(' ') || 'Unnamed stone';
  const weight = result.stone_weight_ct ? `${result.stone_weight_ct} ct` : '--';
  const date  = new Date(result.created_at).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  });

  // These arrays come from the WizardResult type
  // In the mockup they were populated from resData -- here they come from Supabase
  const positive:   string[] = (result as any).positive_factors   || [];
  const limiting:   string[] = (result as any).limiting_factors   || [];
  const structural: string[] = (result as any).structural_factors || [];

  return (
    <>
      {/* Dark overlay */}
      <div
        style={{
          position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)',
          zIndex: 499, opacity: open ? 1 : 0,
          pointerEvents: open ? 'all' : 'none',
          transition: 'opacity 320ms ease',
        }}
        onClick={onClose}
      />

      {/* res-drawer: right-slide container */}
      <div
        ref={drawerRef}
        className={`res-drawer${open ? ' open' : ''}`}
      >
        {/* res-handle: left drag zone -- touch to swipe-close */}
         <div
          ref={drawerRef}
          className={`wo-drawer${open ? ' open' : ''}`}
          onTouchStart={onTouchStart}    // ← whole drawer responds to swipe
          onTouchMove={onTouchMove}
          onTouchEnd={onTouchEnd}
        >
        <div className="wo-handle" />  {/* just visual, no events */}
        <div className="wo-body">...</div>
        </div>

        {/* res-body: the main content area */}
        <div className="res-body">

          {/* res-topbar: band badge + stone name + close button */}
          {/* Converted from the topbar section of openResDrawer() */}
          <div className="res-topbar">
            {/* res-band-badge: colored badge showing the score band */}
            <span
              className="res-band-badge"
              style={{ color, borderColor: color }}
            >
              {result.band}
            </span>
            <span style={{
              fontFamily: 'var(--font-mono)', fontSize: 10,
              letterSpacing: '0.16em', textTransform: 'uppercase',
              color: 'var(--text-muted)', flex: 1,
            }}>
              {stone}
            </span>
            <button className="res-close" onClick={onClose}>✕</button>
          </div>

          {/* res-scroll: scrollable content area */}
          <div className="res-scroll">

            {/* res-hero: large ring + stone name + recommendation */}
            {/* Converted from the res-hero block injected by openResDrawer() */}
            <div className="res-hero">
              <HeroRing pct={pct} color={color} />
              <div>
                {/* res-stone-name: the stone name in display font */}
                <div className="res-stone-name">{stone}</div>
                {/* res-stone-meta: weight, cut, dimensions */}
                <div className="res-stone-meta">
                  {weight} · {result.stone_cut || '--'}<br />
                  {result.stone_dimensions || '--'}
                </div>
                {/* res-rec: the recommendation label in band color */}
                <div className="res-rec" style={{ color }}>{label}</div>
              </div>
            </div>

            {/* ── Positive characteristics ── */}
            {/* Converted from section('Positive Characteristics', listItems(r.positive)) */}
            <Section label="Positive Characteristics">
              {positive.length > 0 ? (
                positive.map((item, i) => <ListItem key={i} text={item} color="var(--gold)" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui)', fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>

            {/* ── Limiting characteristics ── */}
            <Section label="Limiting Characteristics">
              {limiting.length > 0 ? (
                limiting.map((item, i) => <ListItem key={i} text={item} color="#f87171" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui)', fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>

            {/* ── Structural condition ── */}
            <Section label="Structural Condition">
              {structural.length > 0 ? (
                structural.map((item, i) => <ListItem key={i} text={item} color="#fb923c" />)
              ) : (
                <div style={{ fontFamily: 'var(--font-ui)', fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic', padding: '6px 0' }}>
                  None selected
                </div>
              )}
            </Section>

            {/* Date stamp */}
            <div className="res-date">{date}</div>

            {/* Create Service Request button */}
            {/* Converted from the button injected at the bottom of openResDrawer() */}
            {onCreateServiceRequest && (
              <div style={{ marginTop: 24 }}>
                <button
                  onClick={() => onCreateServiceRequest(result)}
                  style={{
                    width: '100%', background: 'var(--gold)', color: 'var(--bg-deep)',
                    border: 'none', padding: 13, fontFamily: 'var(--font-mono)',
                    fontSize: 10, letterSpacing: '0.22em', textTransform: 'uppercase',
                    cursor: 'pointer', transition: 'opacity 180ms ease',
                  }}
                  onMouseOver={e => { (e.currentTarget as HTMLButtonElement).style.opacity = '0.85'; }}
                  onMouseOut={e  => { (e.currentTarget as HTMLButtonElement).style.opacity = '1'; }}
                >
                  + Create Service Request
                </button>
              </div>
            )}

          </div>{/* end res-scroll */}
        </div>{/* end res-body */}
      </div>{/* end res-drawer */}
    </>
  );
}